"""Write docs/VOCABULARY.md from the engine's own word list.

    python tools/vocabulary.py

The engine decides what the words are. It keeps them in src/vine/intents.ts, and
this reads that file, matches every word against the builder of the same name in
vine.py, and writes the table out. It refuses when the two disagree, which is the
whole point of generating the doc instead of typing it.

It needs a checkout of the engine. A member does not have one and does not need
one: docs/VOCABULARY.md is committed and current. Whoever changes the engine runs
this and commits what it writes.

    python tools/vocabulary.py                    ../AdventureGame
    python tools/vocabulary.py C:\\path\\to\\engine  somewhere else
    BLHS_GAME=... python tools/vocabulary.py      or by environment
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(HERE, "docs", "VOCABULARY.md")
INTENTS = os.path.join("src", "vine", "intents.ts")

# the stretch of intents.ts each list lives in
UNION = ("export type Intent =", "export type BeatDeclaration")
RUN_PATHS = ("export type RunPath =", "export type IntentResult")

# a TypeScript comment, which is prose and not vocabulary
COMMENT = re.compile(r"/\*.*?\*/", re.S)

# the headings the doc is laid out under. Each starts at the word named and runs
# until the next, in the engine's own order, so a new word lands under the
# heading above it.
HEADINGS = (
    ("say", "talking"),
    ("guide_to", "showing him where to go"),
    ("pose", "his own body"),
    ("actor_move", "driving somebody else"),
    ("route", "paths and the camera"),
    ("wait", "time and sound"),
    ("movie", "what is on the screen"),
    ("ashore", "boats and panels"),
    ("play", "something that gets a score"),
    ("show", "the world showing the run"),
    ("enter", "going somewhere else"),
    ("get", "the run"),
)

# the closed lists a member has to pick a value out of, and where they are kept
CHOICES = (
    ("view(shot)", "VIEW_SHOTS"),
    ("actor_move(pace=) and lead_to(pace=)", "PACES"),
    ("enter(cover=)", "COVER_OCCASIONS"),
)


def engine_dir(argv):
    if argv:
        return argv[0]
    return os.environ.get("BLHS_GAME") or os.path.join(os.path.dirname(HERE), "AdventureGame")


def _between(src, start, end):
    a = src.index(start)
    return COMMENT.sub("", src[a:src.index(end, a)])


def words(ts):
    """Every word the engine performs, in the order it lists them."""
    return re.findall(r"kind: '([a-z_]+)'", _between(ts, *UNION))


def paths(ts):
    """Every path `get` can be asked for."""
    return re.findall(r"'([a-z_]+)'", _between(ts, *RUN_PATHS))


def panels(ts):
    """The panels `open` will draw."""
    m = re.search(r"kind: 'open'; ui: ([^;]+);", _between(ts, *UNION))
    return re.findall(r"'([a-z_]+)'", m.group(1)) if m else []


def listed(ts, name):
    """One of the engine's small exported lists, as its values."""
    m = re.search(r"export const %s[^=]*=\s*\[(.*?)\]" % name, ts, re.S)
    return re.findall(r"'([a-z_]+)'", m.group(1)) if m else []


def builders(py):
    """Every builder in vine.py: its name, its arguments, and its first line."""
    out = {}
    last = None
    for line in py.split("\n"):
        sig = re.match(r"def ([a-z_]+)\((.*)\):", line)
        if sig:
            last = sig.group(1)
            out[last] = {"args": sig.group(2), "first": ""}
        elif last and not out[last]["first"]:
            first = re.match(r'    """(.+?)("""\s*)?$', line)
            if first:
                out[last]["first"] = first.group(1).strip()
    return out


def render(ts, py):
    """The whole document, as one string."""
    engine = words(ts)
    built = builders(py)

    missing = [w for w in engine if w not in built]
    if missing:
        raise SystemExit(
            "vine.py has no builder for %s, so a member cannot say it. Run "
            "python tools/sync.py" % ", ".join(missing))
    if engine[0] != HEADINGS[0][0]:
        raise SystemExit(
            "the engine now lists %r first and this script starts its headings at "
            "%r. Fix HEADINGS in tools/vocabulary.py." % (engine[0], HEADINGS[0][0]))

    heads = dict(HEADINGS)
    out = [
        "# The words",
        "",
        "Everything an island can ask the game to do. There are %d." % len(engine),
        "",
        "Put `yield` in front of one and it happens. Without the `yield` it builds a",
        "dict, drops it, and the game never hears about it.",
        "",
        "Every place is an anchor name somebody typed in MAPVIS, never an x and a y. A",
        "name the map does not carry is refused on your own line.",
        "",
        "Generated by `python tools/vocabulary.py`. Do not edit this file by hand.",
    ]
    for word in engine:
        if word in heads:
            out += ["", "## %s" % heads[word], "",
                    "| word | how you write it | what it does |", "|---|---|---|"]
        b = built[word]
        out.append("| `%s` | `%s(%s)` | %s |"
                   % (word, word, b["args"], b["first"] or "see vine.py"))

    out += ["", "## what you may pass", "",
            "These are closed lists. Anything else is refused.", ""]
    for where, const in CHOICES:
        out.append("- `%s`: %s" % (where, ", ".join("`%s`" % v for v in listed(ts, const))))
    out.append("- `open(ui)`: %s" % ", ".join("`%s`" % v for v in panels(ts)))
    out.append("- `get(path)`: %s" % ", ".join("`%s`" % v for v in paths(ts)))
    out.append("")
    return "\n".join(out)


def main(argv=()):
    game = engine_dir(list(argv))
    intents = os.path.join(game, INTENTS)
    if not os.path.isfile(intents):
        print("no engine at %s" % game)
        print()
        print("This only runs on a machine with both repositories. If you are a")
        print("member, you do not need it: docs/VOCABULARY.md is already current.")
        return 1

    with open(intents, encoding="utf-8") as f:
        ts = f.read()
    with open(os.path.join(HERE, "vine.py"), encoding="utf-8") as f:
        py = f.read()

    doc = render(ts, py)
    old = None
    if os.path.isfile(DOC):
        with open(DOC, encoding="utf-8") as f:
            old = f.read()
    if doc == old:
        print("docs/VOCABULARY.md  already the same")
        return 0

    if not os.path.isdir(os.path.dirname(DOC)):
        os.makedirs(os.path.dirname(DOC))
    with open(DOC, "w", encoding="utf-8", newline="\n") as f:
        f.write(doc)
    print("docs/VOCABULARY.md  written, %d words" % len(engine_words(doc)))
    return 0


def engine_words(doc):
    """The words the written doc lists, so the line printed is about the file."""
    return re.findall(r"^\| `([a-z_]+)` \|", doc, re.M)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
